### PACs donating to school vouchers or charter schools
pacs_school_choice <- 
  c(
    "STAND FOR CHILDREN, INC",
    "STAND FOR CHILDREN, INC. (IND. EXP. COMM.)",
    "STAND PAC OF TENNESSEE",
    "TENNESSEE FEDERATION FOR CHILDREN",
    "TENNESSEE FEDERATION FOR CHILDREN PAC",
    "AMERICAN FEDERATION FOR CHILDREN INC",
    "AMERICAN FEDERATION OF CHILDREN",
    "AMER FED FOR CHILDREN ACTION FUND  INC",
    "AMERICAN FED. FOR CHILDREN ACTION FUND",
    "TENNESSEANS FOR STUDENT SUCCESS",
    "TENNESSEANS FOR STUDENT SUCCESS INC",
    "TENNESSEANS FOR STUDENT SUCCESS, INC.",
    "STUDENTS FIRST",
    "STUDENTS FIRST PAC",
    "STUDENTSFIRST"
  )


### Big ISP PACs
pac_isp <- 
  c(
    "AT&T",   
    "AT&T PAC",
    "AT&T BROADBAND REFUND", 
    "AT&T TENNESSEE PAC",
    "AT&T WIRELESS SERVICES PAC",
    "AT&T GEORGIA PAC",      
    "AT&T MOBILITY LLC EMPLOYEES PAC",       
    "AT&T (REFUND OF EXPENDITURES)",
    "AT & T PAC TENNESSEE",
    "AT AND T LLC EMPLOYEE PAC",
    "AT &T SERVICES",                              
    "AT&T SERVICES",  
    
    "BELLSOUTH EMPLOYEES",                               
    "REFUND-BELLSOUTH",                                  
    "BELLSOUTH AFFLIATES SERVICES CORP",                 
    "BELLSOUTH",                                         
    "BELLSOUTH PAC",                                     
    "BELLSOUTH GOV RELATIONS",                           
    "BELLSOUTH AFFILIATED SERVICES",                     
    "BELLSOUTH EMPLOYEES GEORGIA PAC",                   
    "BELLSOUTH REFUND",                                  
    "BELLSOUTH EMPLOYEES TN PAC",                        
    "BELLSOUTH EMPLOYEES' TENNESSEE PAC",                
    "BELLSOUTH EMPLOYEES PAC",                           
    "BELLSOUTH EMPLOYEES TENNESSEE POLITICAL ACTION COM",
    "BELLSOUTH EMPLOYEES TENN PAC",                      
    "BELLSOUTH EMPLOYEES TENNESSEE POLITICAL ACTION",    
    "BELLSOUTH TELECOMM. (TYLER HABER), (TYLER HABER)",
    
    "CHARTER COMMUNICATIONS INC., TENNESSEE PAC",
    "CHARTER COMMUNICATIONS",
    "CHARTER COMMUNICATIONS CORPORATIONS, LLC",      
    "CHARTER COMMUNICATIONS, INC. PAC",      
    "CHARTER COMMUNICATIONS (REFUND)",       
    
    "COMCAST CABLE CO.",     
    "COMCAST CORP PAC",      
    "COMCAST CABLE (REFUND)",
    "COMCAST CORP. PAC",     
    "COMCAST CORPORATION POLITICAL ACTION COMMITTEE",
    "COMCAST CORPORATION",   
    "SERVICES CORP COMCAST SHARED",  
    "COMCAST CORP FED PAC",
    "COMCAST SPOTLIGHT ADVERTISING REFUND",  
    "COMCAST REFUND",
    "COMCAST CORP.", 
    
    "VERIZON CORPORATION BUDGET",
    "VERIZON COMMUNICATIONS PAC",    
    "VERIZON COMMUNICATIONS GOOD GOVERNMENT",
    "VERIZON COMMUNICATION GOOD GOVT CLUB",  
    "VERIZON",       
    "VERIZON PAC"
  )

# Law enforcement PACs
pac_police <-
  c(
    "AFRO-AMERICAN POLICE ASSOC",
    "AFRO AMERICAN POLICE ASSOCIATION",
    "CLARKSVILLE POLICE SUPPLY",
    "FRATERNAL ORDER OF POLICE",
    "FRATERNAL ORDER OF POLICE PAC",
    "FRATERNAL ORDER OF POLICE TN STATE LODGE",
    "FRIENDS OF POLICE-FOP PAC",
    "FRIENDS OF POLICE PAC",
    "FRIENDS OF POLICE - VOLUNTEER LODGE#2",
    "INTL BROTHERHOOD OF POLICE OFFICERS 673",
    "KINGSPORT COALITION OF POLICE",
    "MEMPHIS POLICE ASSN. PAC",
    "MEMPHIS POLICE ASSOCIATION",
    "METRO POLICE DEPARTMENT",
    "METROPOLITAN POLICE DEPARTMENT",
    "METROPOLITAN POLICE DEPARTMENT EMPLOYEES CREDIT UN",
    "METROPOLITAN POLICE DEPT. EMPLOYEES CREDIT UNION",
    "PHOENIX LAW ENFORCEMENT ASSOCIATION",
    "PROTECT OUR POLICE PAC",
    "PROTECT OUR POLICE PAC BEGINNING BALANCE",
    "SOUTHERN STATES POLICE BENEVOLENT ASSN PAC",
    "SOUTHERN STATES POLICE BENEVOLENT ASSOCI",
    "SOUTHERN STATES P.B. A.",
    "TN POLICE BENEVOLENT ASSN. INC"
  )

### I intend to eventually split this up into {pac,business,individual} contributions
### from alcohol manufacturers, alcohol wholesalers, alcohol distributors, and alcohol stores.
### There is *so* much money flowing out of the alcohol industry it's stunning.

pac_alcohol_wholesaler <- 
  c(
    "SOUTHERN GLAZER OF TENNESSEE PAC",
    "WHOLESALERS ASSN PAC",              # Beer
    "WSWT POLITICAL ACTION COMMITTEE"    # Wine and spirits
  )

pac_alcohol_producer <-
  c(
    "ANHEUSER BUSCH PAC",
    "BROWN-FORMAN CORP. NON-PARTISAN COMM.",
    "DISTILLED SPIRITS COUNCIL",
    "JACK DANIEL'S PAC",
    "TDG-PAC"                           # Tennessee Distiller's Guild
  )

pac_alcohol_retailer <-
  c(
    "TENNESSEE WINE & SPIRITS RETAILERS GOOD GOV'T FUND"
  )

pac_alcohol <- 
  c(
    pac_alcohol_producer, 
    pac_alcohol_wholesaler, 
    pac_alcohol_retailer
   )

business_alcohol <- 
  c(
    "518 LIQUOR & WINE  LLC",
    "64 LIQUOR & WINE",
    "640 LIQUOR STORE LLC",
    "901 WINE & SPIRITS MARKET",
    "96 LIQUOR AND WINES",
    "ACME LIQUORS",
    "ADMIRAL WINE & SPIRITS",
    "ALLANDALE PACKAGE STORE",
    "AMERICAN WINE & SPIRITS",
    "ARLINGTON LIQUORS",
    "ASHE'S WINE & SPIRITS",
    "ASHE'S WINES & SPIRITS",
    "ATHENS DISTRIBUTING COMPANY - CHATTANOOGA",
    "ATHENS DISTRIBUTING COMPANY - MEMPHIS",
    "ATHENS DISTRIBUTING COMPANY - NASHVILLE",
    "B & B PACKAGE STORE",
    "B & T WHOLESALE",
    "BAILEY'S LLC",
    "BALANCE CORRECTION",
    "BARTLETT WINE & SPIRITS",
    "BARTLETT WINE AND SPIRITS",
    "BEARDEN BEER MARKET LLC",
    "BELLEVUE WINE & SPIRITS LLC",
    "BEST BRANDS",
    "BEVERAGE CONTROL INC",
    "BILL'S PACKAGE  STORE",
    "BLUEGRASS BEVERAGES",
    "BOB'S PACKAGE STORE INC.",
    "BOONES CREEK BEVERAGE",
    "BRENTWOOD WINE & SPIRITS",
    "BROADWAY DISCOUNT LIQUOR",
    "BROADWAY WINE & LIQUOR",
    "BROWN FORMAN CORPORATION",
    "BUCCANEERS IMPORT WINE & SPIRITS",
    "BUD & HAL'S LIQUOR",
    "BUD'S LIQUOR & WINE MART",
    "BUSTER'S LIQUORS & WINES",
    "CAMPBELL STATION WINE & SPIRITS",
    "CASE SELECTS WINE AND SPIRITS",
    "CASON LIQUOR INC",
    "CEDAR BLUFF WINE & SPIRITS",
    "CEDAR CHEST LIQUORS",
    "CEDAR GROVE WINES & LIQOURS",
    "CELEBRATION LIQUORS",
    "CELLAR WINE & SPIRITS",
    "CENTER POINT LIQUORS",
    "CHATTANOOGA WINE & SPIRITS",
    "CHEERS",
    "CHEERS WINE AND SPIRITS",
    "CHUCK'S PACKAGE STORE",
    "CITY LIQUORS",
    "CNG WINE & SPIRITS",
    "COMMONWEALTH SIGNATURE INDUSTRY FUND",
    "COOL SPRINGS WINE & SPIRITS",
    "CORK INC.",
    "CORK INC. DBA CEDAR BLUFF WINE & SPIRITS",
    "CORKS WINE AND SPIRITS",
    "CORNER WINE & SPIRITS",
    "CRISTY'S LIQUOR STORE",
    "CROCKERS FINE WINES",
    "CROSSROADS LIQUORS INC.",
    "D & D LIQUOR SALES",
    "D & V DISTRIBUTING",
    "DEL RIO WINE & SPIRITS",
    "DELTA DISTRIBUTING COMPANY",
    "DISCOUNT LIQUORS & WINES",
    "DISCOUNT WINE & SPIRITS",
    "DISTILLED SPIRITS COUNIL",
    "DIXIE LEE  WINES & LIQUORS",
    "DOE RIVER SPIRITS",
    "DONELSON LIQUORS",
    "DONELSON PIKE LIQUORS",
    "DOWNTOWN WINE AND SPIRITS LLC",
    "E. Z. IN & OUT WINE & LIQUOR",
    "EAST BRAINERD WINE & SPIRITS",
    "ELIXIR SPIRITS LLC",
    "EMPIRE DISTRIBUTORS OF TENN INC - CHATT",
    "EMPIRE DISTRIBUTORS OF TENN INC - KNOXV",
    "EMPIRE DISTRIBUTORS OF TENN INC - MEMPH",
    "EMPIRE DISTRIBUTORS OF TENN INC - NASHV",
    "EXPRESS LIQUORS",
    "EXPRESS WINE & SPIRITS",
    "FARRAGUT WINE & SPIRITS",
    "FARRAGUT WINE & SPIRITS LLC",
    "FIREHOUSE DISCOUNT LIQUORS",
    "FOOTHILLS PLAZA WINES & SPIRITS",
    "FOOTHILLS PLAZA WINES & SPIRITS LLC",
    "FOUR SIXES LIQUORS AND WINES",
    "FRANKLIN WINE & SPIRITS",
    "GASLIGHT LIQUOR SHOPPE INC.",
    "GATEWAY PACKAGE STORE",
    "GEORGETOWN WINE & SPIRITS",
    "GERMANTOWN VILLAGE WINE & LIQUOR",
    "GETWELL LIQUOR LLC",
    "GLAZER'S WHOLESALE",
    "GOOD TIMES WINE SPIRITS & BREW",
    "GOOD TIMES WINE SPIRITS &BREWS",
    "GRAND CRU, LLC",
    "GRAPEVINE WINE & SPIRITS LLC",
    "GRAPEWINE WINE AND SPIRITS LLC",
    "GREAT WINE & SPIRITS",
    "GREEN MEADOW WINE & SPIRITS LLC",
    "GREENACRES PACKAGE STORE",
    "HAPPY HOUR WINE & LIQUOR",
    "HARPETH LIQUORS INC.",
    "HARRY'S WINE & SPIRITS",
    "HARTSVILLE LIQUORS INC.",
    "HEART OF FRAYSER LIQOURS",
    "HICKORY DISCOUNT LIQUOR",
    "HIGH NOTE LIQUORS",
    "HIGHWAY 58 LIQUORS",
    "HILLWOOD VILLAGE LIQUORS INC.",
    "HORIZON WINE & SPIRITS - CHATTANOOGA",
    "HORIZON WINE & SPIRITS - NASHVILLE",
    "I-40 LIQUORS",
    "IMBIBE",
    "IROQUOIS WINE AND SPIRITS",
    "J. BARLEYCORN LLC",
    "JACK DANIEL'S DISTILLERY",
    "JB'S WINE AND SPIRITS INC.",
    "JDC WINES & SPIRITS",
    "JOE'S WINES & LIQUORS",
    "JONESBOROUGH WINE & SPIRITS",
    "KAUFMAN'S LIQUOR STORE",
    "KIMBROUGH TOWERS WINE AND SPIRITS LLC",
    "KIRBY PARKWAY LIQUORS",
    "KIRBY WINES & LIQUORS",
    "KNOXVILLE BEVERAGE CO INC",
    "LAKE LIQUORS",
    "LAMPLIGHT PACKAGE STORE",
    "LANGE'S LIQUOR STORE",
    "LAVERGNE BEVERAGE",
    "LIPMAN BROTHERS",
    "LIQUOR & WINE DEPOT",
    "LIQUOR WORLD OF NASHVILLE INC.",
    "LIQUORS, INC.",
    "MACDOOGAL'S LIQUOR WAREHOUSE",
    "MADDOX ENTERPRISES LLC",
    "MARKET BASKETS LIQUORS, INC.",
    "MARYLAND FARMS WINE & SPIRITS LLC",
    "MEADOWS LIQUOR",
    "MELROSE WINES & SPIRITS",
    "MIDTOWN CORKDORK WINE SPIRITS BEER",
    "MIDTOWN WINE & SPIRITS",
    "MINERAL WELLS PACKAGE STORE",
    "MOON WINE AND SPIRITS",
    "MOUNTAIN LIQUOR LLC",
    "MT JULIET WINE & SPIRITS",
    "MT. JULIET WINE &  SPIRITS",
    "MUDDY WATERS TWO WINE & SPIRITS",
    "MURFREESBORO WINE & SPIRITS",
    "MURRY'S DISCOUNT LIQUOR",
    "NATALIE'S LIQUOR WAREHOUSE",
    "NEWPORT PACKAGE STORE",
    "NORTH ROAN ONE STOP WINE & SPIRITS",
    "NORTHSHORE WINE &  SPIRITS",
    "NORTHSHORE WINE & SPIRITS",
    "NORTHSIDE PACKAGE STORE OF JC, INC.",
    "OASIS PACKAGE STORE",
    "ODEN'S LIQUOR",
    "OLD FORT LIQUOR AND WINE",
    "OLD RAILROAD SPIRITS",
    "ONE STOP WINES & LIQUORS",
    "OOLETWAH WINE & LIQUORS",
    "OPEN SPIGOT LIQUOR LLC",
    "PARIS WEST WOOD WINES AND LIQUORS",
    "PARK LIQUOR",
    "PARK PLACE LIQUOR & WINE",
    "PARKWAY DISCOUNT WINE & LIQUOR",
    "PARKWAY WINE & SPIRITS SPRING HILL",
    "PARTY MART LIQUORS & WINES",
    "PEAVINE WINE & SPIRITS",
    "PLANTATION FINE WINES & SPIRITS",
    "PLAZA PACKAGE STORE",
    "PLEASANT VIEW LIQUORS",
    "POPLAR  WINE & SPIRITS",
    "POPLAR PIKE WINE AND LIQUORS",
    "POPS WINE & LIQUOR",
    "PORT ROYAL LIQUORS",
    "POUR VOUS WINE",
    "RADNOR WINE AND SPIRITS",
    "RALEIGH LIQUORS AND WINES",
    "RED DOG WINE & SPIRITS",
    "RED SPIRITS & WINE",
    "RED SPIRITS AND WINES",
    "RIDGECREST CELLARS WINE & SPIRITS",
    "RILEY'S WINE & SPIRITS",
    "RIVERGATE WINE & LIQUORS",
    "RIVERSIDE WINE & SPIRITS",
    "RIVERSTONE WINE, SPIRITS & BREWS",
    "ROCKY HILL LIQUORS",
    "ROYAL LIQUORS",
    "SAM RIDLEY WINE &  SPIRITS",
    "SANGO WINE & SPIRITS",
    "SEVENTY-TWO WINE & SPIRITS",
    "SINKERS WINE & SPIRITS",
    "SMOKEY MOUNTAIN WINE & SPIRITS",
    "SMYRNA LIQUOR",
    "SOUTH END LIQUORS",
    "SOUTHERN GLAZERS OF TN LLC",
    "SOUTHERN WINE & SPIRITS LLC",
    "SOUTHLAND SPIRITS AND WINE",
    "SPEAKEASY SPIRITS LLC",
    "SPIRITS OF ATOKA",
    "SPIRITS OF TIMBERCREEK",
    "SPIRITS OF TRINITY",
    "STAR DISTRIBUTORS CO.",
    "STATION WINE AND SPRITS",
    "STELLAR CELLAR WINES",
    "STONES RIVER LIQUORS",
    "STRONG BROTHERS LIQUOR STORE",
    "SUMAC LIQUORS",
    "T & T PACKAGE LLC",
    "TAD LIQUORS LLC",
    "TENNESSEE WINE & SPIRITS RETAILERS GOOD GOVERNMENT",
    "TENNESSEE WINE & SPIRITS",
    "TENNESSEE WINE AND SPIRITS RETAILERS",
    "WINE AND SPIRITS WHOLESALERS OF TN",
    "THE BARREL WINE & SPIRITS",
    "THE BARRELL WINE & SPIRITS CO",
    "THE BOTTLE SHOP AT MCEWEN",
    "THE CELLAR",
    "THE CORNER WINE & SPIRITS",
    "THE FORKED VINE WINE & SPIRITS",
    "THE GROVE WINE & SPIRITS",
    "THE LIQUOR BARN",
    "THE LOFT WINE & SPIRITS",
    "THE NEW CORKSCREW",
    "THE ROMULOUS CORPORATION",
    "THE SPIRITS SHOPPE",
    "THE STELLAR CELLAR",
    "THE WINE  SHOPPE AT GREEN HILLS",
    "TMBA",
    "TRIPLE C DISTRIBUTING CO",
    "WEST TENNESSEE CROWN DISTRIBUTING",
    "THE WINE CHAP LLC",
    "THE WNERY OF GERMANTOWN",
    "THOMPSON'S LIQUORS & WINES",
    "TONY'S FINE LIQUORS",
    "TOPSIDE WINE & SPIRITS",
    "TOWNE SQUARE PACKAGE STORE",
    "TURKEY CREEK WINE & SPIRITS",
    "TURNPIKE WINE & SPIRITS",
    "UNCORKED WINE AND SPIRITS",
    "UNIVERSITY LIQUOR AND WINE",
    "UNIVERSITY PACKAGE STORE",
    "VALLEY WINE & SPIRITS",
    "VILLAGE WINES",
    "VINE & BARRELL, LLC",
    "VINTAGE WINE & SPIRTS",
    "VINTAGE WINES & SPIRITS",
    "WAREHOUSE LIQUORS",
    "WAREHOUSE LIQUORS SPRINGFIELD",
    "WAYNE'S WINE & LIQUOR",
    "WEISS LIQUORS, INC.",
    "WEST END DISCOUNT LIQUORS & WINES, INC.",
    "WEST MAIN WINE & LIQUORS",
    "WEST MEADE WINE & LIQUOR MART INC.",
    "WHISKERS WINE & SPIRITS",
    "WHITE BRIDGE ROAD WINE AND LIQUORS",
    "WHITEHAVEN LIQUORS",
    "WILKINSON LIQUOR STORE",
    "WINE AND SPIRITS CELLAR, LLC",
    "WINE  CELLAR",
    "WINE & SPIRITS UNLIMITEED"
)
  
individual_alcohol <-
  c(
    "BARZIZZA, JOHN",
    "BERNARD, THOMAS",
    "CANALE, CHRIS",
    "CHRISTENBERRY, H.E.",
    "COX, ANDY",
    "CRAIG, ELIZABETH",
    "DETTWILLER, FRED",
    "GARRETT, BOB",
    "GILBERTSON, ROBERT",
    "HAND, CHARLES",
    "HAND, RAY",
    "HENNIGAN, BOB",
    "HOOPER, JOHN",
    "JOHNSON, ANDREW",
    "LAROCCA, AL",
    "LEEBERN, III, DONALD",
    "LIPMAN, ROBERT",
    "LUCCHESI, PAUL",
    "MILNER, MICHAEL",
    "MOORE, HEIDI",
    "PETRONE, ROBERT",
    "SAMPSON, LAUREN",
    "SONNENBERG, CHARLES",
    "TURNER, SCOTT",
    "WILLIAMS, ROBERT",
    "WOOD, MALCOLM"
  )

### I likewise need to split this up into {PACs, Businesses, Individuals}.  
### Private prisons PAC's get a *LOOOOTTT* of money from their employees 
pac_private_prisons <- 
  c(
    "CORRECTIONS CORPORATION OF AMERICA INC PAC",
    "CORRECTIONS CORPORATION OF AMERICA",
    "CORECIVIC, INC.",
    "CORECIVIC, INC. PAC",
    "ADAMS, ROBERT",
    "AHLEFEDT, LOUISA",
    "ALVARADO, DONNA",
    "ANDREWS, WILLIAM",
    "ARIOLA, MARCELO",
    "ARNOLD, JOYCE",
    "BARNARD, PATRICIA C.",
    "BAXTER, JOHN D.",
    "BETANCOURT, FRANK",
    "BLAIR, LANE S.",
    "BLIEK, JACOB",
    "BRADLEY, JODY",
    "BRILL, HOYT",
    "BURDETT-MEYERS, ANGELA",
    "CABILING, LOUIS",
    "CARSON, STACEY",
    "CARTER, COLE",
    "CASON, STACEY B.",
    "CAULFIELD, JOHN",
    "CHRISTMAS, JAMES",
    "COLLINS, BRIAN",
    "COLLINS, CHARLOTTE",
    "CONRY, STEVEN",
    "CONWAY, JEFFREY A.",
    "COPE, JASON B.",
    "CORRENTI, JOHN D",
    "CRADDOCK, SCOTT L.",
    "CROUCH, RICHARD C.",
    "DEBUSE, TIMOTHY",
    "DECONCINI, DENNIS",
    "DEMLER, KARIN S.",
    "DENNIS, ROBERT",
    "DEROSA, CHARLES",
    "DIGGS, ANNE L.",
    "DONAHUE, MICHAEL J.",
    "DOTSON, STEPHEN",
    "DURBIN, THOMAS",
    "EASTERLING, JOSEPH",
    "EICH, MARY J.",
    "ELLIS, JASON T.",
    "ELROD JR., BENNIE",
    "ENGLAND, STEVEN",
    "FERGUSON, JOHN D.",
    "FLOYD, MARK",
    "FUQUA, JAMES",
    "GARFINKLE, DAVID",
    "GARNER, JACK",
    "GILCHRIST GRANT, LOUISE",
    "GILKEY, CHARLES",
    "GIMESH, JOHN",
    "GOODRICH, BARRY",
    "GRANDE, ANTHONY L",
    "GRANT, LOUISE G",
    "GRIDER, VIRGINA",
    "GROOM, STEVEN E",
    "HAMMONDS, BRIAN",
    "HART, PENNY",
    "HININGER, DAMON",
    "HOLLIS, JAY",
    "HORNE, JOHN",
    "HUTTO, T D",
    "JABLONSKI, PATRICK",
    "JACOBI, CHARLES M",
    "JOHNS, BUDEA",
    "KAISER, STEPHEN W",
    "KEETON, CHARLES",
    "KEITH, JIM",
    "KEITH, TIMOTHY B.",
    "KENNEDY, JAMES",
    "KLINE, HELEN",
    "KOEHN, BRIAN",
    "KOEHN, CINDY",
    "KUPFERER, THOMAS",
    "KURTZ, ROBERT",
    "LANZ, JOHN",
    "LAPPIN, HARLEY G.",
    "LAUGHLIN, JOSEPH V",
    "LESTER, AMANDA",
    "LIGHT, ELIJAH",
    "LINDAMOOD, CHERRY",
    "LONG, THOMAS",
    "MACDONALD, JAMES S",
    "MARASCO, LOU",
    "MARIUCCI, ANNE L",
    "MARKHAM, EDDY",
    "MARSHALL, JR, THURGOOD",
    "MARTIN, CHARLES",
    "MAYBERRY, LUCIBETH N.",
    "MCDONALD, JAMES S",
    "MELENDEZ, CARLOS",
    "MERRILL, STEPHEN",
    "METCALF, NATASHA",
    "MORGAN, JAY T.",
    "MULLENGER, TODD",
    "MURRAY, DONALD",
    "MYERS, KEVIN",
    "ODOM, ANTHONY",
    "OVERBY, CHARLES",
    "OVERTON, BEVERLY",
    "OWEN, STEVEN",
    "PARKER, MARY ANN",
    "PETERSON, THOMAS C",
    "PFEIFFER, JOHN",
    "PHILLIPS, BOBBY",
    "PORTER, KIM",
    "PREDIERI, TIM",
    "PRESCOTT, LINDA",
    "PUGH, MICHAEL",
    "QUINLAN, J. MICHAEL",
    "REGENS, BRADLEY",
    "ROBINSON, JOHN",
    "RUSSELL, JOSEPH",
    "SAMBERG, MICHAEL",
    "SCHOMIG, JAMES",
    "SCHUMANN, DEBORAH",
    "SHANBLUM, LAURIE",
    "SHAW, ROBERT S",
    "SHAW, THOMAS N.",
    "SHUSTER, BEN H",
    "SHUTTLEWORTH, JEAN H.",
    "SLOAN, BRIGHAM F.",
    "SMITH, WILLIAM",
    "SPIEGL JR, JOSEPH N",
    "SPIVEY, RICHARD",
    "STALEY, LINDA",
    "STEWART, DONALD W",
    "STOVALL, RANDALL",
    "SULLIVAN, CINDY S",
    "SWENSON, DAREN M",
    "SWINDLE, PATRICK",
    "TAPIA, ROBERT",
    "TAYLOR, JOSEPH L",
    "THOMAS, GEORGE",
    "THOMAS, GREGORY T",
    "THOMAS, PENNY",
    "THOMPSON, RONALD",
    "TIGHE, JOHN",
    "TURNER, MELODY",
    "VAUGHN, MAYLEE",
    "VERHUIST, BART",
    "WASHBURN, RUSSELL",
    "WELCH, JOHN",
    "WHITE, KIM M",
    "WIGGINS, KENNETH",
    "WILEY, JEREMY",
    "WILKINSON, TIMOTHY"
  )



pac_cannabis <- 
  c(
    "LABCANNA BIOSCIENCES, INC",
    "TNCANNA, LLC",
    "TN MEDICAL CANNABIS TRADE ASSOCIATION",
    "TENNESSEE GROWER'S COALITION",
    "TMCTA PAC",
    "TMCTA"
  )

business_cannabis <- 
  contrib %>% 
  filter(Recipient.Name %in% pac_cannabis) %>% 
  filter(Source == "Business") %>% 
  select(Contributor.Name) %>% 
  pull()


pac_pharma_mfg <- 
  c(
    "JOHNSON & JOHNSON EMPLOYEES GOOD GOVERNMENT FUND",
    "JOHNSON & JOHNSON POLITICAL ACTION COMMITTEE",
    "MERCK & CO",
    "MERCK & CO.",
    "MERCK & CO. INC.",
    "MERCK & CO. INC. EMPLOYEES PAC",
    "MERCK SHARP & DOHME  CORP",
    "MERCK SHARP & DOHME CORP",
    "MERCK SHARP & DOHME CORP.",
    "NOVARTIS",
    "NOVARTIS FINANCE COR",
    "NOVARTIS FINANCE CORPORATION",
    "NOVARTIS PAC",
    "NOVARTIS PHARMACEUTICALS CORP.",
    "NOVARTIS PHARMACEUTICALS CORPORATION",
    "NOVARTIS POLITICAL ACTION COMMITTEE",
    "PFIZER INC.",
    "PFIZER INC. PAC",
    "PFIZER PAC",
    "ROCHE DIAGNOSTICS CORPORATION PAC (ROCHE DXPAC)",
    "ASTELLAS PHARMA US, INC.",
    "VERTEX PHARMACEUTICALS INCORPORATED",
    "KING PHARMACEUTICALS, INC. PAC"
)   

pac_pharma_sales <-
  c(
    "INDEPENDENT PHARMACY PAC OF TENNESSEE",
    "AMERICAN PHARMACY COOPERATIVE INC.",
    "TENNESSEE PHARMACEUTICAL PAC",
    "HOMETOWN PHARMACY PAC",
    "INDEPENDENT PHARMACY PAC",
    "TENNESSEE PHARMACISTS PAC",
    "CAREMARK RX INC",
    "INDEPENDENT PHARMACY PAC OF TENNESSEE",
    "AMERICAN PHARMACY COOPERATIVE INC."
  )

business_pharma <-
  c(
    "ADVANVCED SPECIALITY PHARMACY",
    "ANDERSON COMPOUNDING PHARMACY INC",
    "ANDERSON PHARMACY",
    "AVENTIS PHARMACEUTICALS INC. PAC",
    "BAGGETT PHARMACY",
    "CLARKSVILLE PHARMACY LLC",
    "CLARKSVILLE PHARMACY, LLC",
    "COOKEVILLE PHARMACY LLC",
    "COOKEVILLE PHARMACY, LLC",
    "CORLEY'S PHARMACY",
    "DUNCAN'S PHARMACY",
    "DUNKLAU PHARMACY HOLDINGS LLC",
    "EDDIE'S PHARMACY",
    "FIRST PHARMACY SERVICES LLC",
    "FISHER PHARMACY & GIFTS",
    "FOUNTAIN PLAZA PHARMACY, LLC",
    "GIBBS PHARMACY INC",
    "GRAY PHARMACY INC",
    "GREENBRIER PHARMACY, LLC",
    "HAMILTON DISCOUNT PHARMACY",
    "HARTSVILLE PHARMACY",
    "HEALTHCARE PHARMACY INC",
    "HERNDON PHARMACY LLC",
    "HERNDON PHARMACY, LLC",
    "H & S PHARMACIES 1&2",
    "INFINITY PHARMACY, LLC",
    "JOHNSON COUNTY PHARMACISTS INC.",
    "KIZER PHARMACY",
    "MCCORMICK'S PHARMACY INC",
    "MIKE'S PHARMACY",
    "MILBURN PHARMACY",
    "MINCHIE PHARMACY",
    "NASHVILLE PHARMACY SERVICES LLC",
    "NASHVILLE PHARMACY SERVICES, LLC",
    "NOVARTIS PHARMACEUTICALS CORP.",
    "NOVARTIS PHARMACEUTICALS CORPORATION",
    "PARKLAND HEALTH MART PHARMACY",
    "PHARMACIA CORP. EMPLOYEES PAC",
    "PHARMACIA CORPORATION EMPLOYEES (PEPAC)",
    "PHARMACY PLUS PROGRAMS, LLC",
    "PLEASANT VIEW PHARMACY",
    "PREFERRED PHARMACY, INC",
    "PREFERRED PHARMACY TELLICO GREENS LLC",
    "RAINES PHARMACY",
    "R & K PHARMACY, INC",
    "SIGNAL MOUNTAIN PHARMACY",
    "TENNESSEE PHARMACISTS ASSOCIATION",
    "TERRY'S PHARMACY",
    "TOWN AND COUNTRY PHARMACY",
    "VOLUNTEER PHARMACY, INC",
    "WILSON SAV-MOR PHARMACY",
    "WINKLES PHARMACY"
    )

pac_legislature_candidate <-
  c(
    "RAAMPAC",                  # Lt. Governor Ron Ramsey
    "MCPAC",                    # Lt. Governor Randy McNally
    "CAM PAC",                  # House speaker Cameron Sexton
    "CAS-PAC",                  # House speaker Glen Casada
    "HARWELL PAC",              # House speaker Beth Harwell
    "LAMBERTH PAC",             # William Lamberth (R - Portland)
    "MPAC",                     # Mark Norris  (R - Collierville)
    "JACK - PAC",               # Jack Johnson (R - Franklin)
    "QUEST PAC",                # Bill Ketron (R - Murfreesboro)
    "MUMPAC",                   # Jason Mumpower
    "VOLUNTEER PAC",            # Bill Frist
    "THE SPEAKER'S FUND",       # Jimmy Naifeh
    "MCCORMICK PAC",            # Gerald McCormick
    "GREEN PAC",                # Mark Green
    "HAILE PAC",                # Ferrell Haile
    "RED STATE PAC",            # Brian Kelsey
    "FAISON'S FREEDOM",         # Jeremy Faison
    "AKBARI PAC",               # Sen. Raumesh Akbari (R - Memphis)
    "JIM TRACY LEADERSHIP PAC", # Jim Tracy
    "THE OVERBEY PAC",          # Sen. Doug Overbey, (R - Maryville)
    "ODOM PAC",                 # Gary Odom
    "TENNESSEE TOMORROW PAC",   # Roy Herron
    "FITZ PAC",                 # Craig Fitzhugh
    "JOHNSON VICTORY PAC",      # Curtis Johnson
    "KURITA MAJORITY PAC",      # Rosalind Kurita
    "SPEAKER EMERITUS LEADERSHIP FUND", # Jimmy Naifeh
    "RIMPAC",                   # Diane Black
    "MAJORITY TENNESSEE",       # Don Sundquist
    "TENNESSEE KEEP YOUR LEGISLATURE EFFICIENT PAC", # Sara Kyle
    "BOW-PAC",                  # Bo Watson
    "PB PAC",                   # Sen Paul Bailey
    "KEYPAC",                   # Ken Yager
    "BELL PAC",                 # Mike Bell
    "THREE STAR PAC",           # Andy Berke
    "BRIGGS PAC",               # Richard Briggs
    "NASH PAC",                 # Jon Lundberg
    "JOE PAC",                  # Joe Carr
    "INVICTUS PAC",             # John Ray Clemmons
    "BECPAC",                   # Becky Massey
    "KPAC",                     # Kent Williams
    "TN-K PAC",                 # Kevin Brooks
    "LEADERSHIP PIONEERS",      # Robin Smith
    "STEVENS PAC",              # John D. Stevens
    "CAMP PAC",                 # Karen Camper
    "MGC PAC",                  # Michael Curcio
    "PRO BUSINESS AND JOBS PAC",# Andrew Farmer
    "FUNK LEADERSHIP PAC",      # Glenn Funk
    "WEST TN CREAM OF THE CROP", # Tim Wirgau
    "JCB PAC",                  # Clark Boyd
    "DURHAM PAC",               # Jeremy Durham
    "YELLOW ROSE PAC",          # Sara Kyle
    "BOWLING PAC",              # Janice Bowling
    "CURTISS PAC",              # Charles Curtiss
    "REEVES FAMILY PAC",        # Shane Reeves
    "ENVISION TENNESSEE",       # Sen. Jeff Yarbrough
    "TRISTAR PAC",              # Darren Jernigan
    "KEVPAC",                   # Kevin Vaughan
    "FREEDOM PAC",              # Mae Beavers
    "BEAR PAC",                 # Randy Rinks
    "JUDDPAC",                  # Judd Matheny
    "REEDY PAC",                # Jay Reedy
    "RURAL TENNESSEE SPEAKS PAC", # Jay Reedy again...
    "MARSHA PAC",               # Marsha Blackburn
    "OVERMOUNTAIN PAC",         # Matthew Hill
    "RIGHT TENNESSEE",          # Glen Casada
    "MARSH FOR TENNESSEE BUSINESS PAC", # Pat Marsh
    "RY - PAC",                 # Ryan Williams
    "SHEILA'S LIBERTY PAC",     # Sheila Butts
    "TURNER PAC",               # Mike Turner
    "TODD FOR A BETTER TENNESSEE", # Chris Todd
    "JOBS4TN PAC"               # Bill Haslam
    
    # This list isn't even remotely done, sadly
    
  )

pac_legislature_party <-
  c(
    "TENNESSEE LEGISLATIVE CAMPAIGN COMMITTEE", # The State Committee for the Tennessee Republican Party
    "SENATE REPUBLICAN CAUCUS",
    "TENNESSEE REPUBLICAN CAUCUS",
    "HOUSE DEMOCRATIC CAUCUS",
    "TENNESSEE DEMOCRATIC PARTY",
    "SENATE DEMOCRATIC CAUCUS",
    "HOUSE REPUBLICAN CAUCUS",
    "HOUSE SENATE DEMOCRATIC CAUCUS"
   )

pac_payday_loans <-
  c(
    "TENNESSEE FIRST"
   )

pac_tobacco <-
  c(
    "ALTRIA CLIENT SERVICES LLC",
    "ALTRIA GROUP INC. PAC",
    "BROWN &WILLIAMSON TOBACCO CORP. PAC",
    "CIGAR-PAC",
    "GENERAL CIGAR COMPANY, INC",
    "GENERAL CIGAR COMPANY, INC.",
    "GENERAL CIGAR CO.",
    "LORILLARD TOBACCO COMPANY PUBLIC AFFAIRS COMMITTEE",
    "LORILLARD TOBACCO COMPANY PAC",
    "NATIONAL TOBACCO COMPANY, L.P.",
    "NATIONAL TOBACCO COMPANY LP",
    "RAI SERVICES COMPANY",
    "RJR PAC REYNOLDS AMERICAN INC.",
    "R.J REYNOLDS PAC",
    "RJ REYNOLDS TOBACCO COMPANY",
    "TENNESSEE REYNOLDS AMERICAN INC. PAC",
    "TENNESSEE R. J. REYNOLDS PAC",
    "US SMOKELESS TOBACCO COMPANY",
    "UST LLC EXECUTIVE",

    "BELLE MEADE PREMIUM CIGAR OPERATING ACCO",
    "CIGAR VENTURES",
    "DISCOUNT CIGARETTE & TOBACCO OUTLET",
    "SAM'S DISCOUNT TOBACCO",
    "TENNESSEE TOBACCO SALES INC"
  )

individual_tobacco <-
  contrib %>%
  filter(Source == "Individual",
         Recipient.Name %in% pac_tobacco) %>%
  filter(grepl("ALTRIA|US SMOK|ALTIRA|ATLRI|ALRIA|ALTRIS|PHILIP MORRIS|ALTRA|ALTIA|ALTRAI|PM|PHILIP|MORRIS|ALTRIC|RJ REYNLODS|RJ  REYNOLD|SANTA FE|RJR|RJ REN|REYNOLDS|RJ REYNOLD|ALCS", Contributor.Employer)) %>%
  select(Contributor.Name) %>%
  unique()

pac_pharma_drugtests <- c("AEGIS SCIENCES CORP")



